twitter:
    consumer_key: ''
    consumer_secret: ''
    access_token_key: ''
    access_token_secret: ''
    twittername: 'Htmlcoin Tip Bot'
    twitterkeyword: 'htmlcointipbot'
log:
  file: tipbot.log
rpc:
  host: localhost
  port: 4888
  user: htmlcoinrpc
  pass: pass
  prefix: ''
coin:
  withdrawal_fee: .01
  min_withdraw: 1
  min_confirmations: 6
  min_tip: 1
  min_rain: 1
  short_name: ' HTML'
  full_name: htmlcoin 
webadmin:
  enabled: false
  port: 8080
  users:
    unek: supersecretpassword
    admintwo: password
commands:
  help:
    pm: true
    channel: true
  tip:
    pm: true
    channel: true
  balance:
    pm: true
    channel: true
  withdraw:
    pm: true
    channel: true
  address:
    pm: true
    channel: true
  terms:
    pm: true
    channel: true
  rain:
    pm: false
    channel: true
    rain_on_last_active: 0 # amount in seconds. rain tips will fall only on users active within x seconds. leave 0 for no such behavior.
messages:
  error: 'Sorry %name%, something went wrong.'
  no_funds: "Sorry %name%, you don't have enough funds (you're %short%%short_name% short)"
  not_identified: '%name%: You need to be identified with NickServ to tip.'
  tipped: '%from% tipped %to% %amount%%short_name%! "tweet %nick% help" to participate.'
  balance: '%name% has %balance%%short_name%.'
  balance_unconfirmed: '%name% has %balance%%short_name% (unconfirmed: %unconfirmed%%short_name%)'
  deposit_address: Your deposit address %address%
  withdraw_too_small: 'Sorry %name%, you need to withdraw at least %min_withdraw%%short_name% (you have %balance%%short_name%)'
  invalid_address: 'Sorry %name%, the address you specified is invalid (%address%).'
  tip_too_small: 'Sorry %from%, your tip to %to% (%amount%%short_name%) is too small (min. %min_tip%%short_name%).'
  tip_self: "Sorry %name%, you can't tip yourself!"
  invalid_amount: 'Sorry %name%, "%amount%" is not a correct amount.'
  withdraw_success: 
    - '%name%: %amount%%short_name% has been withdrawn from your account to %address%'
    - 'You have been charged %withdrawal_fee%%short_name% withdrawal fee.'
    - 'Transaction %transaction% completed.'
  help:
    - 'Tag HtmlcoinTipBot and use following commands. If Twitter states Tweet already sent, add 5 characters to end of tweet like so ->'
    - 'HtmlcoinTipBot balance - displays your current wallet balance'
    - 'HtmlcoinTipBot address - displays %full_name%  your deposit address'
    - 'HtmlcoinTipBot withdraw <%full_name% address> - withdraws your entire wallet balance (minus %withdrawal_fee%%short_name% withdrawal fee)'
    - 'HtmlcoinTipBot tip <nick> <amount> - sends the specified amount of %full_name% to nickname'
    - 'HtmlcoinTipBot terms - displays terms and conditions for using %nick%'
  terms:
    - 'There are no fees to use %nick%, with the exception of %withdrawal_fee%%short_name% fee on withdrawals.'
    - 'In no event shall %nick% be responsible in the event of lost, stolen or misdirected funds.'
